### ISSUE TITLE
Envio de servicios / hoja de ruta por email

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#10]
#### Envio de servicios / hoja de ruta por email
Detalle: En este módulo se podrá enviar por email los servicios / hoja de ruta del día. El sistema por defecto sugerirá los destinatarios especificados en el ABM con posibilidad quitar o agregar nuevos.

**Comment by danim27** [comment]
para el envío de mail se toma en cuenta los mismos criterios que para exportar.
-Si es una hoja de ruta el usuario debe realizar un búsqueda previa con fechaDesde, fechaHasta y móvil.
En el caso de la exportación/envío de mails de servicios y hojas de ruta, se tienen en cuenta también que la búsqueda previa haya arrojado resultados.
