### ISSUE TITLE
ABM Email Destinatarios

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#11]
#### ABM Email Destinatarios
Detalle: En este módulo se visualizará un listado de los emails previamente configurados. A su vez también se podrá dar de alta uno nuevo como también dar de baja o modificar uno existente.

**Comment by danim27** [comment]
@luchanz esto va a ser una tabla Mail (ID, direccion_correo)? se guarda también guarda el nombre del destinatario? o estos mails corresponden a afiliados, personal (doctor o chofer)? Si no es así, ¿a quien se les va a enviar mails?

**Comment by danim27** [comment]
#10

**Comment by luchanz** [comment]
@danim27 La idea de estos emails es que ellos puedan enviar el detalle de los servicios del día a la obra social. Los destinatarios son los de la Obra social mismo.
