### ISSUE TITLE
ABM Móvil

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#13]
#### ABM Móvil
Detalle: En este módulo se visualizará un listado de los móviles existentes. A su vez también se podrá dar de alta uno nuevo como también dar de baja o modificar uno existente.

Un móvil estará representado por:
* Campo ID Móvil (número autogenerado por el sistema único y no editable)
* Campo Patente
* Campo Descripción

**Comment by danim27** [comment]
según la tabla Movil de la BD anterior tiene:
- ID
- Código
- Radio
- Patente
Le agregué esos atributos y adicionalmente:
- Estado
- Fecha baja
