### ISSUE TITLE
Servicios abiertos - filtro hora desde / hora hasta

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#32]
@danim27 que filtra el hora desde / hora hasta? 

![captura de pantalla 2015-05-31 a las 20 39 32](https://cloud.githubusercontent.com/assets/1274244/7904515/28055d34-07d5-11e5-9e57-a49f1e6ac10f.png)

**Comment by danim27** [comment]
ya está resuelta la búsqueda con filter para los inputs con valores vacíos o null. Con el combo de moviles no tuve éxito, sugiero agregar un botón de clear como el que tiene el input de las localidades.
