### ISSUE TITLE
Servicios abiertos - filtro entre calles

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#33]
##### Se hace la búsqueda por fecha 01/01/2000 - 01/01/2020
![captura de pantalla 2015-05-31 a las 20 43 15](https://cloud.githubusercontent.com/assets/1274244/7904527/ba6efaea-07d5-11e5-8cf6-f4d1880822cf.png)
##### Se filtra por calle
![captura de pantalla 2015-05-31 a las 20 43 36](https://cloud.githubusercontent.com/assets/1274244/7904528/be056f2c-07d5-11e5-8824-2ad19d21c618.png)
##### Se elimina el filtro por calle, pero no vuelve a traer los registros sin calle.
![captura de pantalla 2015-05-31 a las 20 43 38](https://cloud.githubusercontent.com/assets/1274244/7904529/c004cab6-07d5-11e5-96ed-96806b704c88.png)

**Comment by luchanz** [comment]
@danim27 esto ocurrió también con movil? por eso habías sacado la opción nula?

**Comment by danim27** [comment]
#32
