### ISSUE TITLE
Intransitable pasa a ser zona roja

### ISSUE THREAD

**Issue by danim27** [luchanz/ext-med-angular#37]
- Para esto hay que modificar el test de insert de Servicios ya que los campos deambula e intransitable no fueron considerados en el test.
- Setear en c/servicio zonaRoja=intransitable.

**Comment by danim27** [comment]
@luchanz como resolvemos esto? 
tanto el atributo deambula como intransitable fueron ignorados en el test porque hasta el momento de la realización del mismo no se había definido que iba a pasar con esos atributos.
El test de InsertServiciosTest ya fue implementado? si es así, tengo que realizar otro test para cambiar el valor de zona roja de los servicios anteriores por el valor de intransitable?

**Comment by luchanz** [comment]
@danim27 tranquila, incluilo en el test porque las implementaciones que vinimos haciendo son de prueba. Todavía nada salio a producción

**Comment by danim27** [comment]
Ok, lo incluyo entonces.
