### ISSUE TITLE
Se quita la columna hora de despacho de los servicios abiertos y la búsqueda.

### ISSUE THREAD

**Issue by danim27** [luchanz/ext-med-angular#41]
@luchanz  si lo saco de los servicios abiertos, entonces la hora de despacho nunca se setea con el camioncito? 
ó se puede setear solo cuando se edita un servicio? 
lo pongo como dato obligatorio para poder finalizar un servicio (al igual que la hora arribo/salida), o la hora de despacho no es obligatoria para realizar esta acción?

**Comment by luchanz** [comment]
@danim27 la hora de despacho se quita de todos lados.

**Comment by danim27** [comment]
@luchanz no, la usaban. Era un atributo nuevo que te habían pedido, según lo dice el doc de relevamiento: "PARA FINALIZAR UNA ORDEN DEBE TENER MOVIL ASIGNADO, HORARIO DESPACHO, HORARIO DE ARRIBO Y HORARIO DE SALIDA DEL DOMICILIO"

**Comment by luchanz** [comment]
@danim27 okay, si, ahora se dieron cuenta que no tiene sentido anotar el horario de despacho
