### ISSUE TITLE
Trabaja el dia se habilita si no esta en condiciones de trabajar

### ISSUE THREAD

**Issue by danim27** [luchanz/ext-med-angular#43]
@luchanz como es esto?

**Comment by luchanz** [comment]
@danim27 Si, esto solo lo anote, tenemos que pensar como hacerlo, pero la idea es que:

Si esta en condiciones de trabajar, no ponen fecha porque vuelve de inmediato.
Si no esta en condiciones de trabajar, ponen fecha para cuando va a en condiciones.
