### ISSUE TITLE
Linea separatoria entre todos los asignados y no asignados

### ISSUE THREAD

**Issue by danim27** [luchanz/ext-med-angular#44]
@luchanz en que pantalla y a que se refiere el asignado y no asignado

**Comment by luchanz** [comment]
@danim27 esto es lo mismo que me pidieron en aba en su momento y al final no lo hicimos.
Lo que ellos quieren es poder ver visualmente en la tabla de servicios abiertos, tener diferenciado cuales estan asignados y cuales no, es decir:

servicio asignado
servicio asignado
servicio asignado
servicio asignado
------------------------
servicio no asignado
servicio no asignado
servicio no asignado
servicio no asignado

**Comment by danim27** [comment]
@luchanz sigo sin entender que significa que un servicio este asignado y a que está asignado.. a un móvil?

**Comment by luchanz** [comment]
@danim27 si, a un movil
