### ISSUE TITLE
Ponerle tooltip a entre calles en ordenes abiertas

### ISSUE THREAD

**Issue by danim27** [luchanz/ext-med-angular#47]

**Comment by luchanz** [comment]
@danim27 basicamente esto es para que si la columna entre calles es demasiada larga no deforme la tabla, es decir,

Si en la columna entre calles aparece:
San carlos esta ubicada entre paseo colon y san martin de areco.

Esto provocaria que visualmente la fila de la tabla se vea
San carlos esta 
ubicada entre 
paseo colon y 
san martin de 
areco.

Entonces para evitar esto lo que queremos es que en la tabla se vea:

San carlos esta 
ubicada entre...

Y cuando te ubicas arriba de "San carlos esta ubicada entre..." sale un tooltip con:
"San carlos esta ubicada entre paseo colon y san martin de areco."

Se entiende?

**Comment by danim27** [comment]
Ahora se entiende mejor, por eso te preguntaba, no me habías dicho en que pantalla va el tooltip...
Lo había implementado en el input entreCalles del alta del servicio y no le veía utilidad.
En fin, entonces lo agrego en ambas búsquedas de servicios?

**Comment by luchanz** [comment]
Genial, si si,  en la busqueda de servicios y servicios abiertos. Ahora no estoy en la ofi pero creo que entre calles aparece en las 2 tablas. En v2 esta en alguna otra tabla?

**Comment by danim27** [comment]
Me parece que solo en esas dos.

**Comment by luchanz** [comment]
Ok, avisame cualquier cosa
