### ISSUE TITLE
Agregar los files a resources asi los versionamos

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#55]
Agregar al proyecto en /ext-med-rest-services/src/test/resources
export_hojaderuta.pdf
logo-ext-med.jpg
export_servicios.pdf

**Comment by danim27** [comment]
De todos estos solo logo-ext-med.jpg es un file resource, el resto de los files se crean (si no existen) en el dir indicado en el path de la tabla 'properties' . 
Leer la indicación que agregué en el readme (en los inserts de la tabla properties), hay que setear los paths tal como lo hicimos en ABA.
