### ISSUE TITLE
Export y envio de emails no funcionan

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#56]
@danim27 configure todo tal como https://github.com/luchanz/ext-med-angular/blob/Version-2/README.md especifica pero al hacer una búsqueda no exporta ni envia emails.
Al presionarlo la aplicación no hace nada. Y ni en el log de angular ni del jboss arroja nada de nada

![captura de pantalla 2015-06-16 a las 17 54 06](https://cloud.githubusercontent.com/assets/1274244/8194242/c3ba5b76-1450-11e5-9c45-e59754d16c2f.png)

Por otro lado ni bien entro a la pantalla esos botones deberían estar inhabilitados si previamente no busque nada

**Comment by danim27** [comment]
los botones EXPORT PDF/ENVIAR MAIL sí están deshabilitados ni bien cargas la página. Se habilita n con la primera búsqueda.
De todos modos, no andaba porque dejó de funcionar cuando agregué el tooltip ya que ambos usan el atributo data-toggle, tuve que forzar el dropdown para que funcione.
