### ISSUE TITLE
En la busqueda de localidades no filtra por fecha baja.

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#59]
![captura de pantalla 2015-06-17 a las 14 31 11](https://cloud.githubusercontent.com/assets/1274244/8214175/bc07942c-14fd-11e5-8e5d-c37c8a620b15.png)
![captura de pantalla 2015-06-17 a las 14 31 34](https://cloud.githubusercontent.com/assets/1274244/8214176/bc240652-14fd-11e5-913c-8897505931c2.png)

**Comment by danim27** [comment]
v3
