### ISSUE TITLE
Búsqueda de Localidades - No abre el modal de busqueda de provincia

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#61]
![captura de pantalla 2015-06-17 a las 14 53 11](https://cloud.githubusercontent.com/assets/1274244/8214609/bd5dab1a-1500-11e5-9d00-95e929c6c122.png)

**Comment by luchanz** [comment]
@danim27 ahora si abre el modal, pero al seleccionar la provincia no la baja al form

**Comment by luchanz** [comment]
@danim27 Ahora baja la provincia, pero no filtra por provincia...
![captura de pantalla 2015-06-18 a las 17 12 20](https://cloud.githubusercontent.com/assets/1274244/8241089/92faea12-15dd-11e5-8c0c-e0cfe0dd8654.png)

**Comment by danim27** [comment]
f298aaebd0832d99ebcdadf39c8fa0946fecd32d
3fc205e408a580bae72a77f10f194ea3a60c9f0f
