### ISSUE TITLE
Búsqueda de Localidades - Quedan escritos los input de busquedas al ingresar nuevamente a la pantalla

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#62]
![captura de pantalla 2015-06-17 a las 14 54 55](https://cloud.githubusercontent.com/assets/1274244/8214627/e4be871a-1500-11e5-83ca-1110369bff52.png)
![captura de pantalla 2015-06-17 a las 14 55 00](https://cloud.githubusercontent.com/assets/1274244/8214629/e4ee641c-1500-11e5-8389-6992dce49977.png)
![captura de pantalla 2015-06-17 a las 14 55 02](https://cloud.githubusercontent.com/assets/1274244/8214628/e4ee4270-1500-11e5-9a56-3c22493fb9cc.png)

**Comment by luchanz** [comment]
@danim27 

Esto tambien ocurre en: 
* Búsqueda de provincias
* Búsqueda de personal
* Búsqueda de móviles

**Comment by danim27** [comment]
v3
