### ISSUE TITLE
SI el movil existe, por mas que este dado de baja, no te debe dejar crear otro con el mismo nro movil

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#64]
![captura de pantalla 2015-06-17 a las 15 26 50](https://cloud.githubusercontent.com/assets/1274244/8215316/7fdf16c0-1505-11e5-8b8a-06ceb5868b11.png)
![captura de pantalla 2015-06-17 a las 15 27 01](https://cloud.githubusercontent.com/assets/1274244/8215317/7ff487c6-1505-11e5-969f-37576756177a.png)

**Comment by luchanz** [comment]
@danim27 esto mismo ocurre en:
* ABM de localidades
* ABM de provincias

**Comment by luchanz** [comment]
@danim27 en el ABM de personal no tiene la posibilidad de ingresar codigo, con lo cual en la base de datos no lo esta guardando, pero sin embargo en la tabla muestra el codigo.
![captura de pantalla 2015-06-17 a las 15 37 34](https://cloud.githubusercontent.com/assets/1274244/8215518/ca652580-1506-11e5-908a-db79429f6e2a.png)

Igualmente mas alla de esto, no seria mejor que tanto Provincias, Localidades, Personal y Moviles tengan un codigo autogenerado y no editable?

**Comment by danim27** [comment]
Igualmente mas alla de esto, no seria mejor que tanto Provincias, Localidades, Personal y Moviles tengan un codigo autogenerado y no editable? // Es lo ideal, y lo que sugerí en el momento de hacer la migración a postgres. Pero según la especificación y las tablas en la BD, el cliente cargaba sus propios códigos en el alta de cada entidad.
Hay que reveer las entidades en cuestión.

**Comment by luchanz** [comment]
@danim27 tal vez es mas simple hacer que el codigo sea autoincremental y sacarlo de las altas y fin...

**Comment by luchanz** [comment]
@danim27 en la migracion usas el codigo para algo? o en todo te manejas con las fk?

**Comment by danim27** [comment]
Si. El código lo guardo, y tengo varias queries que usan los códigos.

**Comment by danim27** [comment]
El código ya no se usa en Provincias, Localidades, Personal.
Sí se utiliza en móviles, se resolvió dejar el código como auto inc (no es PK, sigue estando el ID), creando un sequence en postgres (124208f86be2f403231c726c7c387857c289d355) que arranca a partir de 62 (61 es el mayor código que tienen en la tabla de móviles vieja).
