### ISSUE TITLE
Informe de servicios realizados (PDF)

### ISSUE THREAD

**Issue by luchanz** [luchanz/ext-med-angular#8]
#### Informe de servicios realizados (PDF)
Detalle: En la Búsqueda de un servicio se podrá generar un informe PDF ordenado por fecha y agrupado por Sección / Dependencia. Este informe estará compuesto por las siguientes columnas:
* N° de servicio
* Apellido y nombre
* N° de ficha
* N° de artículo
* Días otorgados
* Reinicio laboral
* Próxima consulta
* Informe / observaciones

**Comment by danim27** [comment]
#10
